### ISSUE TITLE
Not scanning when using venv python path either

### ISSUE THREAD

**Issue by therealsbeve** [zxix/stable-diffusion-pickle-scanner#1]
Getting this error when trying to use the venv python path instead of the regular python command:

At line:1 char:64
+ ... table-diffusion-webui\venv\Scripts\python.exe" pickle_scan.py models  ...
+                                                    ~~~~~~~~~~~~~~
Unexpected token 'pickle_scan.py' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by TheEliteGeek** [comment]
I was also getting this as well when using PowerShell terminal. It seems to work when using cmd prompt.

**Comment by therealsbeve** [comment]
Thank you! This worked wonderfully. Don't know what's wrong with PS but CMD worked just fine.

**Comment by zxix** [comment]
Yes, haven't built this to work with Powershell. If someone would like to open a PR for it I would definitely be open to reviewing.
